### ISSUE TITLE
YaruMasterDetailPage wish-list

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_widgets.dart#255]
- [x] full control over master list tiles
  - replace "icon" & "title" with a "tile" builder?
  - tooltips, semantics, badges, animations, custom tiles, ...
- [x] full control over detail page app bar
  - replace "title" with an "app bar" builder?
  - leading icon, trailing actions, bottom widget, ...
- [x] themable constraints, padding, spacings, ...

**TODO**: update the docs when all the refactoring is done!

**Comment by Feichtmeier** [comment]
> replace "title" with an "app bar" builder?

I don't think we need this if each page is itself either a column (appbar/page) or a scaffold (appbar, body) :)

**Comment by jpnurmi** [comment]
i'm afraid i screwed up that possibility with the animations... :fearful: 

[appbar-vs-page.webm](https://user-images.githubusercontent.com/140617/194766244-ac5f73e4-0bbc-4459-b475-58c049f26a58.webm)

**Comment by Feichtmeier** [comment]
I dont understand

**Comment by jpnurmi** [comment]
Bad screencast quality. :slightly_frowning_face: The problem is that the app bar gets included in the page transitions if it's inside the content.

**Comment by Feichtmeier** [comment]
Hm but what about pages that make use of model classes in the app bar?
I think it would be better to include them on the page directly in a scaffold

Otherwise you need to suck in the model inside the appBarBuilder

Widget appBarBuilder(BuildContext context) {
final model = context.watch<MyModel>();
return AppBar(flexibleSpace: TextField(onChanged: ()=> model.bla = .... ));
}
and so on

**Comment by jpnurmi** [comment]
It's a bit hackish but one possibility to exclude `AppBar` from the page transition is to wrap it with a `Hero` widget. What makes it a bit inconvenient is that `Scaffold.appBar` requires a `PreferredSizeWidget` so you can't pass `Hero` directly...

```dart
Scaffold(
  appBar: PreferredSize(
    preferredSize: Size(
      0,
      Theme.of(context).appBarTheme.toolbarHeight ?? kToolbarHeight,
    ),
    child: Hero(
      tag: 'no-animation',
      child: AppBar(
        title: const Text('Title'),
      ),
    ),
  ),
  body: const MyPage(),
)
```

**Comment by Feichtmeier** [comment]
IMO that the app bar is included in the transition is not bad
It's part of the page

**Comment by jpnurmi** [comment]
Ok! Then we can just remove the app bar. 👌

**Comment by Feichtmeier** [comment]
Maybe we could create a yarupage as a recommended page which includes scaffold and your hero trick?
