### ISSUE TITLE
yaru_widgets 2.0 checklist

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_widgets.dart#280]
- [x] "widgets everywhere"
- [x] bring compact layout on par with master-detail (tile builder)
- [ ] add compact layout vs. master-detail overview with illustrative wireframes
- [x] review and fix outdated example snippets
- [x] update readme
- [x] tests
- [ ] ~~unify borders~~ #588
- [x] #202
- [x] rename compact layout to navigation page
- [x] port all relevant apps and examples to use the new title bars
- [x] update screenshot #589
- [ ] ~~add missing brief class descriptions~~ #587

anything else? please add any missing items :)

**Comment by Jupi007** [comment]
Maybe add a few tests to check if everything works as expected?

**Comment by jpnurmi** [comment]
If master-detail has "tiles", what does the compact layout have? How would you call the items that consist of an icon and a text label?

**Comment by Jupi007** [comment]
Well, looking at the exact traduction of "tile", imo it would also fit for the navigation rail items.
"Item" could also be used btw, but I prefer "tile" :)

**Comment by jpnurmi** [comment]
I exposed `(_)YaruNavigationRailItem` without renaming it for now. There's some related naming discussion ongoing at https://github.com/ubuntu/yaru_widgets.dart/pull/284#issuecomment-1275801935.

**Comment by jpnurmi** [comment]
Can someone help create master-detail and navi-rail wireframes? Perhaps something similar to the dock mode etc. in the settings app?

**Comment by Jupi007** [comment]
@Muqtxdir as you did "settings" dock mode images, maybe you could be interested by doing the wireframes?

**Comment by Muqtxdir** [comment]
hi everyone 👋

by wireframes do you mean recolorable SVG(s)?

**Comment by Muqtxdir** [comment]
ah thanks for the explanation @jpnurmi. could you share some actual screenshots as well, I'll use that as reference for wireframes

**Comment by jpnurmi** [comment]
Awesome, thank you! The [software](https://github.com/ubuntu-flutter-community/software) and [settings](https://github.com/ubuntu-flutter-community/settings) apps are great examples even though the content on the right side could be anything. yaru_widgets offer generic building blocks to easily create apps with either of these layouts.

| navi-rail (software) | master-detail (settings) |
|---|---|
| ![image](https://user-images.githubusercontent.com/140617/195832593-a205f6d4-1d6a-48b7-beca-20552e9ab5cd.png) | ![image](https://user-images.githubusercontent.com/140617/195832622-4c7ada00-480d-4a30-83bb-7c752a088da0.png) |

**Comment by Jupi007** [comment]
The software screenshot isn't exactly representative of the current navigation rail look :)
@Muqtxdir if you can, run the example app of this repository. You will be able to switch between layout with a switch on the first page.

**Comment by Muqtxdir** [comment]
ok,noted. thanks everyone.ill look into this one once i reach home

**Comment by jpnurmi** [comment]
Are we in good enough shape to publish a pre-release e.g. 2.0.0-beta.1?

**Comment by Jupi007** [comment]
I'm working on the checkboxes, if we can add them in beta.2, I want to say yes.

**Comment by whiskeyPeak** [comment]
I looked at the current yaru widget selection and there doesn't seem to be a yaru themed textfield widget. It'd be nice if it could make itself into the 2.0 release. I can open an adjacent issue to further discuss the design language if it is something that needs to be implemented :)

@jpnurmi

**Comment by Feichtmeier** [comment]
Well ideally we should be able to do this with yaru.dart, I hope. I try tomorrow. If not... we need our own :S

**Comment by Jupi007** [comment]
What's the problem with the current material text entries? 🤔

**Comment by Feichtmeier** [comment]
too thick border

**Comment by Jupi007** [comment]
Oh, okay.
Well yes, this should be fixed in the theme so 🙂

**Comment by whiskeyPeak** [comment]
> Well ideally we should be able to do this with yaru.dart, I hope. I try tomorrow. If not... we need our own :S

Ah oops, didn't see that package. O_O

**Comment by jpnurmi** [comment]
Any takers for unifying the borders? Or do we even need it for 2.0 because it's probably not going to be a breaking change because it won't affect the API?

**Comment by Jupi007** [comment]
What do you exactly mean with unify? Unify the borders color?

**Comment by jpnurmi** [comment]
Hmm, I wish I had included a link to the discussion wherever it was... I think around the time when `YaruBorderContainer` was added.

But basically yeah, there are quite a few different variants of `colorScheme.onSurface.withOpacity(0.x)` with slightly different opacity levels being used as border and divider colors across `yaru.dart` and `yaru_widgets.dart`. The idea was to unify them and make use of `ThemeData.dividerColor` and `DividerTheme.color` where possible.

**Comment by Jupi007** [comment]
> divider color should be fine for all. if we want it to be lighter, we should change this in yaru.dart

I agree 👍

**Comment by jpnurmi** [comment]
Here's the earlier discussion I was referring to: https://github.com/ubuntu/yaru_widgets.dart/pull/333

**Comment by Feichtmeier** [comment]
Looking at the list I don't think any critical things are left to release 2.0.0 :) 
I can update Settings later
What about the firmware-updater? :)

**Comment by jpnurmi** [comment]
I'm also happy with how things are. :+1: Docs and stuff can be improved later. :)

**Comment by Feichtmeier** [comment]
> I'm also happy with how things are. :+1: Docs and stuff can be improved later. :)

😎 Ok
Can you do it? I think it's your honour since you pimped this repo up from the ground 🚀

**Comment by jpnurmi** [comment]
- https://github.com/ubuntu/yaru_widgets.dart/issues/587
- https://github.com/ubuntu/yaru_widgets.dart/issues/588
- https://github.com/ubuntu/yaru_widgets.dart/pull/589
